import { constants } from 'node:fs/promises';
import childProcess from 'child_process';
import { Buffer, }from 'buffer';
import { describe, expect, test, } from '@jest/globals';
import Storage from '~/class/Storage';

describe('[Class] Storage;', () => {
  test('Storage should be able to complete basic file operations.', async () => {
    const storage = new Storage('/tmp/test');
    await storage.mkdir('test-directory-operation');
    await storage.addBuffer('test-directory-operation/operation.txt', Buffer.from('perform related diectory operations'));
    let ans = await storage.exists('test-directory-operation1/operation.txt');
    expect(ans).toBe(false);
    await storage.cp('test-directory-operation', 'test-directory-operation1', { recursive: true, });
    ans = await storage.exists('test-directory-operation1/operation.txt');
    expect(ans).toBe(true);
    await storage.rmdir('test-directory-operation');
    await storage.rmdir('test-directory-operation1');
    ans = await storage.exists('test-directory-operation1/operation.txt');
    expect(ans).toBe(false);
    ans = await storage.exists('test-directory-operation/operation.txt');
    expect(ans).toBe(false);
    expect(childProcess.execSync('ls /tmp/test/').toString()).toMatch('');
    await storage.addBuffer('test-file-operation/operation.txt', Buffer.from('perform related file operations.'));
    ans = await storage.exists('test-file-operation/operation.txt');
    expect(ans).toBe(true);
    let data = await storage.readData('test-file-operation/operation.txt');
    expect(data.toString()).toMatch('perform related file operations.');
    let buffer = await storage.readBufferPiece('test-file-operation/operation.txt', 8, 7);
    expect(buffer.toString()).toMatch('related');
    await storage.writeBufferPiece('/test-file-operation/operation.txt', 21, Buffer.from('OPERATIONS'));
    data = await storage.readData('test-file-operation/operation.txt');
    expect(data.toString()).toMatch('perform related file OPERATIONS.');
    await storage.appendData('test-file-operation/operation.txt', ' etc');
    let stats = await storage.getStats('test-file-operation/operation.txt');
    const beforeNs = stats.mtimeNs;
    data = await storage.readData('test-file-operation/operation.txt');
    expect(data.toString()).toMatch('perform related file OPERATIONS. etc');
    await storage.truncate('test-file-operation/operation.txt', 21);
    data = await storage.readData('test-file-operation/operation.txt');
    await expect(storage.access('test-file-operation/operation.txt', constants.R_OK)).resolves.not.toThrow();
    await storage.chmod('test-file-operation/operation.txt', '775');
    await storage.chown('test-file-operation/operation.txt', 502, 0);
    expect(data.toString()).toMatch('perform related file');
    await storage.rename('test-file-operation/operation.txt', 'test-file-operation/operation1.txt');
    data = await storage.readData('test-file-operation/operation1.txt');
    expect(data.toString()).toMatch('perform related file');
    await storage.rename('test-file-operation/operation1.txt', 'test-file-operation/operation.txt');
    ans = await storage.exists('test-file-operation/operation.txt');
    expect(ans).toBe(true);
    ans = await storage.exists('test-file-operation/link.txt');
    expect(ans).toBe(false);
    await storage.link('test-file-operation/operation.txt', 'test-file-operation/link.txt');
    const realpath = await storage.realpath('test-file-operation/link.txt');
    expect(realpath).toMatch('/private/tmp/test/test-file-operation/operation.txt');
    ans = await storage.exists('test-file-operation/link.txt');
    expect(ans).toBe(true);
    data = await storage.writeBuffer('test-file-operation/link.txt', Buffer.from('new content'));
    data = await storage.readData('test-file-operation/link.txt');
    expect(data.toString()).toMatch('new content');
    stats = await storage.getStats('test-file-operation/operation.txt');
    const afterNs = stats.mtimeNs;
    expect(afterNs > beforeNs).toBe(true);
    const watcher = await storage.watch('test-file-operation/operation.txt');
    expect(() => Storage.unwatchSync(watcher)).not.toThrow();
    const files = await storage.readdir('test-file-operation', { recursive: true, });
    expect(JSON.stringify(files)).toMatch('[\"link.txt\",\"operation.txt\"]');
    const paths = await storage.glob('**/*');
    expect(JSON.stringify(paths)).toMatch('[\"test-file-operation\",\"test-file-operation/link.txt\",\"test-file-operation/operation.txt\"]')
    await storage.cp('test-file-operation/operation.txt', 'test-file-operation/operation-backup.txt');
    const diskOccupy = await storage.diskOccupy('test-file-operation');
    expect(diskOccupy).toBe(64);
    await storage.remove('test-file-operation/link.txt');
    await storage.remove('test-file-operation/operation.txt');
    await storage.remove('test-file-operation/operation-backup.txt');
    const diskUsage = await storage.diskUsage();
    expect(diskUsage.total).toBe(250790436864);
    expect(childProcess.execSync('ls /tmp/test').toString()).toMatch('');
    expect(childProcess.execSync('ls /tmp/test/.index').toString()).toMatch('');
  });
});
