import childProcess from 'child_process';
import { Buffer, }from 'buffer';
import { describe, expect, test, } from '@jest/globals';
import Storage from '~/class/Storage';

describe('[Class] Storage;', () => {
  test('Storage should be able to complete basic file operations.', async () => {
    const storage = new Storage('/tmp/immense');
    let ans = await storage.exists('test-file-operation/operation.txt');
    // expect(ans).toBe(false);
    await storage.addBuffer('test-file-operation/operation.txt', Buffer.from('perform related file operations.'));
    // ans = await storage.exists('test-file-operation/operation.txt');
    // expect(ans).toBe(true);
    let data = await storage.readData('test-file-operation/operation.txt');
    expect(data.toString()).toMatch('perform related file operations.');
    let buffer = await storage.readBufferPiece('test-file-operation/operation.txt', 8, 7);
    expect(buffer.toString()).toMatch('related');
    await storage.writeBufferPiece('/test-file-operation/operation.txt', 21, Buffer.from('OPERATIONS'));
    data = await storage.readData('test-file-operation/operation.txt');
    expect(data.toString()).toMatch('perform related file OPERATIONS.');
    await storage.appendData('test-file-operation/operation.txt', ' etc');
    let stats = await storage.getStats('test-file-operation/operation.txt');
    const beforeNs = stats.mtimeNs;
    data = await storage.readData('test-file-operation/operation.txt');
    expect(data.toString()).toMatch('perform related file OPERATIONS. etc');
    await storage.truncate('test-file-operation/operation.txt', 21);
    data = await storage.readData('test-file-operation/operation.txt');
    expect(data.toString()).toMatch('perform related file');
    await storage.rename('test-file-operation/operation.txt', 'test-file-operation/operation1.txt');
    data = await storage.readData('test-file-operation/operation1.txt');
    expect(data.toString()).toMatch('perform related file');
    await storage.rename('test-file-operation/operation1.txt', 'test-file-operation/operation.txt');
    ans = await storage.exists('test-file-operation/link.txt');
    // expect(ans).toBe(false);
    await storage.link('test-file-operation/operation.txt', 'test-file-operation/link.txt');
    ans = await storage.exists('test-file-operation/link.txt');
    // expect(ans).toBe(true);
    data = await storage.writeBuffer('test-file-operation/link.txt', Buffer.from('new content'));
    data = await storage.readData('test-file-operation/link.txt');
    expect(data.toString()).toMatch('new content');
    stats = await storage.getStats('test-file-operation/operation.txt');
    const afterNs = stats.mtimeNs;
    expect(afterNs > beforeNs).toBe(true);
    const watcher = await storage.watch('test-file-operation/operation.txt');
    expect(() => Storage.unwatchSync(watcher)).not.toThrowError();
    // await storage.remove('test-file-operation/link.txt');
    // await storage.remove('test-file-operation/operation.txt');
    expect(childProcess.execSync('ls /tmp/immense').toString()).toMatch('');
    // expect(childProcess.execSync('ls /tmp/immense/.index').toString()).toMatch('');
  });
});
